# Use an official Node.js runtime as a parent image
FROM node:16

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install Angular CLI globally (if not already installed)
RUN npm install -g @angular/cli

# Install project dependencies
RUN npm install

# Copy the Angular app files to the container
COPY ./dist ./dist

# Expose the port that the application will run on
EXPOSE 4200

# Define the command to start the Angular application
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]
